### ISSUE TITLE
klaviyo.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#362] opened 2022-09-05 14:37 UTC
This issue outlines breakage for requests associated with the `klaviyo.com` domain.

- https://shopyalehome.com (last verified 2022-09-05)
  - site renders blank
  - requests required
    - `www.klaviyo.com/media/js/public/klaviyo_subscribe.js`
- https://fearofgod.com (last verified 2022-09-05)
  - site renders blank
  - requests required
    - `www.klaviyo.com/media/js/public/klaviyo_subscribe.js`

**Comment by sammacbeth** [comment] 2022-11-09 08:54
Further `klaviyo.com` breakage:

- https://manage.kmail-lists.com/subscriptions/
  - site renders blank
  - requests required: https://static-app.klaviyo.com/fender/83919.401de5abb7927d48beb1.js

Root cause is missing entity data - kmail-lists.com and klaviyo.com share the same owner. This has been fixed in tracker-radar (https://github.com/duckduckgo/tracker-radar/pull/168) and will be resolved in the next blocklist update.

**Comment by chas-klaviyo** [comment] 2022-11-23 16:25
Hi all, we have an additional issue that we opened up around this root issue: https://github.com/duckduckgo/privacy-configuration/issues/551 cc: @sammacbeth @GuiltyDolphin

**Comment by jdorweiler** [comment] 2023-08-09 20:41
- https://footweartruth.com/  email signup form is missing

**Comment by shakyShane** [comment] 2023-09-03 13:37
- email signup form missing from https://andieswim.com/en-gb/pages/fit-finder too

**Comment by dharb** [comment] 2024-01-17 15:56
Additional Klaviyo breakage:
- https://github.com/duckduckgo/privacy-configuration/issues/1277 - kidsguide.com
- https://github.com/duckduckgo/privacy-configuration/pull/1748 - muc-off.com, paria.cc

**Comment by tagawa** [comment] 2024-04-18 05:51
Email signup form missing on https://usafacts.org/signup/

**Comment by kzar** [comment] 2024-05-30 15:46
Email signup form missing on https://holdonbags.com/

**Comment by kzar** [comment] 2024-05-31 14:32
Email signup form missing on nestlenutritionstore.com

**Comment by kzar** [comment] 2024-05-31 15:16
Email signup form missing on https://dreamfarm.com

**Comment by laghee** [comment] 2024-06-13 17:04
Closing out as **archived** since we updated to a new transparency system in PR #2137

**Closed by laghee** 2024-06-13 17:04 UTC
