### ISSUE TITLE
Cannot login on chase.com

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#988] opened 2023-06-12 18:06 UTC
- chase.com (2023-06-12)
  - cannot login
  - https://app.asana.com/0/1200277586140538/1204290835495482/f
  - disabling `runtimeChecks` mitigates
  

- chase.com (2024-01-31)
  - cannot login
  - https://app.asana.com/0/1200277586140538/1206482222142936/f
  - adding default UA mitigates

**Comment by solomonkenny** [comment] 2023-06-16 18:50
HI GuiltyDolphin - can you add other banks that are experiencing breakages?

**Comment by dharb** [comment] 2023-06-16 20:12
Hi @solomonkenny - we’re currently working on a broader solution for this type of breakage, as it seems to be increasingly prevalent. If you’re aware of any specific bank websites that are experiencing breakage, I’d be very grateful if you could share them so I can perform a root cause analysis and get them fixed.

**Comment by laghee** [comment] 2024-06-13 16:57
Closing out as **archived** since we updated to a new transparency system in PR #2137

**Closed by laghee** 2024-06-13 16:57 UTC
